import { defineConfig } from "oxlint";

const ignorePatterns = [
  "**/dist",
  "**/build",
  "**/.output",
  "**/.turbo",
  "**/.vite",
  "**/coverage",
  "**/*.gen.*",
  "**/*.generated.*",
  "**/generated",
  "**/__generated__",
  "**/*.d.ts.map",
  "**/bun.lock",
];

export default defineConfig({
  env: {
    browser: true,
    es2022: true,
    node: true,
  },
  ignorePatterns,
  overrides: [
    {
      files: ["**/routeTree.gen.ts"],
      rules: {
        "react/react-compiler": "off",
        "unicorn/no-abusive-eslint-disable": "off",
      },
    },
    {
      files: ["**/*.{test,spec}.{ts,tsx,js,jsx}"],
      rules: {
        "promise/prefer-await-to-then": "off",
      },
    },
  ],
  plugins: ["typescript", "oxc", "import", "promise", "react", "jsx-a11y"],
  rules: {
    "func-style": "off",
    "import/no-cycle": "warn",
    "import/no-duplicates": "error",
    "import/no-self-import": "error",
    "jsx-a11y/alt-text": "error",
    "jsx-a11y/anchor-has-content": "error",
    "jsx-a11y/aria-props": "error",
    "jsx-a11y/aria-role": "error",
    "jsx-a11y/aria-unsupported-elements": "error",
    "jsx-a11y/control-has-associated-label": "error",
    "jsx-a11y/heading-has-content": "error",
    "jsx-a11y/html-has-lang": "error",
    "jsx-a11y/iframe-has-title": "error",
    "jsx-a11y/interactive-supports-focus": "error",
    "jsx-a11y/label-has-associated-control": "error",
    "jsx-a11y/no-autofocus": "warn",
    "jsx-a11y/no-redundant-roles": "error",
    "jsx-a11y/role-has-required-aria-props": "error",
    "jsx-a11y/role-supports-aria-props": "error",
    "jsx-a11y/tabindex-no-positive": "error",
    "no-use-before-define": "off",
    "promise/no-multiple-resolved": "error",
    "promise/no-return-wrap": "error",
    "promise/param-names": "error",
    "promise/prefer-await-to-then": "error",
    "promise/valid-params": "error",
    "react/exhaustive-deps": "error",
    "react/jsx-key": "error",
    "react/no-danger": "error",
    "react/no-object-type-as-default-prop": "error",
    "react/no-unstable-nested-components": "error",
    "react/react-compiler": "warn",
    "react/rules-of-hooks": "error",
    "typescript/consistent-type-imports": "error",
    "typescript/no-floating-promises": "error",
    "typescript/no-import-type-side-effects": "error",
    "typescript/no-misused-promises": "error",
    "typescript/no-unnecessary-type-assertion": "warn",
    "typescript/switch-exhaustiveness-check": "error",
    "unicorn/no-abusive-eslint-disable": "error",
    "unicorn/no-document-cookie": "error",
    "unicorn/no-invalid-fetch-options": "error",
    "unicorn/no-useless-undefined": "error",
  },
  settings: {
    "jsx-a11y": {
      components: {
        Button: "button",
        Checkbox: "input",
        Input: "input",
        Label: "label",
        NativeSelect: "select",
        Textarea: "textarea",
      },
    },
    react: {
      linkComponents: [{ attribute: "to", name: "Link" }],
    },
  },
});
