/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleAccountRouteImport } from './routes/$locale.account'
import { Route as LocaleAdminRouteImport } from './routes/$locale.admin'
import { Route as LocaleForgotPasswordRouteImport } from './routes/$locale.forgot-password'
import { Route as LocaleResetPasswordRouteImport } from './routes/$locale.reset-password'
import { Route as LocaleSignInRouteImport } from './routes/$locale.sign-in'
import { Route as ApiOtelV1TracesRouteImport } from './routes/api/otel/v1/traces'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAccountRoute = LocaleAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminRoute = LocaleAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleForgotPasswordRoute = LocaleForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleResetPasswordRoute = LocaleResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSignInRoute = LocaleSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiOtelV1TracesRoute = ApiOtelV1TracesRouteImport.update({
  id: '/api/otel/v1/traces',
  path: '/api/otel/v1/traces',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/account': typeof LocaleAccountRoute
  '/$locale/admin': typeof LocaleAdminRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale/': typeof LocaleIndexRoute
  '/api/otel/v1/traces': typeof ApiOtelV1TracesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/account': typeof LocaleAccountRoute
  '/$locale/admin': typeof LocaleAdminRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale': typeof LocaleIndexRoute
  '/api/otel/v1/traces': typeof ApiOtelV1TracesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/account': typeof LocaleAccountRoute
  '/$locale/admin': typeof LocaleAdminRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale/': typeof LocaleIndexRoute
  '/api/otel/v1/traces': typeof ApiOtelV1TracesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/account'
    | '/$locale/admin'
    | '/$locale/forgot-password'
    | '/$locale/reset-password'
    | '/$locale/sign-in'
    | '/$locale/'
    | '/api/otel/v1/traces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/account'
    | '/$locale/admin'
    | '/$locale/forgot-password'
    | '/$locale/reset-password'
    | '/$locale/sign-in'
    | '/$locale'
    | '/api/otel/v1/traces'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/account'
    | '/$locale/admin'
    | '/$locale/forgot-password'
    | '/$locale/reset-password'
    | '/$locale/sign-in'
    | '/$locale/'
    | '/api/otel/v1/traces'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  ApiOtelV1TracesRoute: typeof ApiOtelV1TracesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/account': {
      id: '/$locale/account'
      path: '/account'
      fullPath: '/$locale/account'
      preLoaderRoute: typeof LocaleAccountRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin': {
      id: '/$locale/admin'
      path: '/admin'
      fullPath: '/$locale/admin'
      preLoaderRoute: typeof LocaleAdminRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/forgot-password': {
      id: '/$locale/forgot-password'
      path: '/forgot-password'
      fullPath: '/$locale/forgot-password'
      preLoaderRoute: typeof LocaleForgotPasswordRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/reset-password': {
      id: '/$locale/reset-password'
      path: '/reset-password'
      fullPath: '/$locale/reset-password'
      preLoaderRoute: typeof LocaleResetPasswordRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/sign-in': {
      id: '/$locale/sign-in'
      path: '/sign-in'
      fullPath: '/$locale/sign-in'
      preLoaderRoute: typeof LocaleSignInRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/otel/v1/traces': {
      id: '/api/otel/v1/traces'
      path: '/api/otel/v1/traces'
      fullPath: '/api/otel/v1/traces'
      preLoaderRoute: typeof ApiOtelV1TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocaleRouteChildren {
  LocaleAccountRoute: typeof LocaleAccountRoute
  LocaleAdminRoute: typeof LocaleAdminRoute
  LocaleForgotPasswordRoute: typeof LocaleForgotPasswordRoute
  LocaleResetPasswordRoute: typeof LocaleResetPasswordRoute
  LocaleSignInRoute: typeof LocaleSignInRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAccountRoute: LocaleAccountRoute,
  LocaleAdminRoute: LocaleAdminRoute,
  LocaleForgotPasswordRoute: LocaleForgotPasswordRoute,
  LocaleResetPasswordRoute: LocaleResetPasswordRoute,
  LocaleSignInRoute: LocaleSignInRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  ApiOtelV1TracesRoute: ApiOtelV1TracesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
